# Copyright 2020 Wayback Archiver. All rights reserved.
# Use of this source code is governed by the GNU GPL v3
# license that can be found in the LICENSE file.
#
name: Snapcraft

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
  workflow_dispatch:

permissions: write-all

jobs:
  snapcraft:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set env & Print rivet version
        shell: bash
        run: |
          version=$(git describe --tags `git rev-list --tags --max-count=1` | sed -e 's/v//g')
          sed -i "s/version: 'git'/version: '${version}'/g" snapcraft.yaml

      - id: build
        name: Build Snap
        uses: snapcore/action-build@v1
        with:
          snapcraft-channel: stable

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: rivet-snap
          path: ${{ steps.build.outputs.snap }}

      - uses: snapcore/action-publish@v1
        name: Release Snap
        if: github.repository == 'wabarc/rivet'
        with:
          store_login: ${{ secrets.SNAPCRAFT_TOKEN }}
          snap: ${{ steps.build.outputs.snap }}
          release: stable
